Ft app-views
zbahati/blogApp pull request #6
Opened 2023-10-31 22:17 UTC by zbahati

2023-10-31 23:55 UTC, Munsa1 requested changes
Hi @zbahati, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Implemented Views As Given In The Wireframes :heavy_check_mark: 
Clean CodeBase :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-31 23:55 UTC, Munsa1 commented on app/views/posts/index.html.erb
> +                <p><%= comment.Text %></p>
- [ ] Its a requirement that here we use `five_recent_comments` created in the post model to render 5 most recent comments in the `app/views/posts/index.html.erb` page. Kindly do so.

2023-10-31 23:55 UTC, Munsa1 commented on app/views/users/index.html.erb
> +  <% end %>
- [ ] (Optional) Using partials is a better option as a practice instead of using `@objects.each`. Consider it for future projects

2023-11-01 10:15 UTC, prolajumokeoni approved these changes
Hi @zbahati 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Updated recent comments👍🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 08:42 UTC, merged